spring:
  datasource:
    url: jdbc:mysql://localhost:3306/handbook_crm
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: handbook_mongo
      repositories:
        enabled: true
