spring:
  datasource:
    url: jdbc:mysql://localhost:3306/handbook_crm
    username: hb_user
    password: Handbook@11
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: handbook_mongo
      repositories:
        enabled: true
